Accueil:
    path: /accueil
    controller: App\Controller\IndexController::Accueil

Modification:
  path: /modification-medicament
  controller: App\Controller\IndexController:Modification

Ajout:
  path: /ajout-medicament
  controller: App\Controller\IndexController:Ajout

Suppression:
  path: /suppression-medicament
  controller: App\Controller\IndexController:Suppression
