CREATE PROC PS_CountPraticien AS
BEGIN
	SELECT COUNT(*)
	FROM PRATICIEN
END
GO

CREATE PROC PS_AffichePraticien AS
BEGIN
	SELECT PRA_NUM AS [N� Identifiant], PRA_NOM AS [Nom], PRA_PRENOM AS [Prenom], TYP_LIBELLE AS [Fonction] 
	FROM PRATICIEN PRA INNER JOIN TYPE_PRATICIEN TPRA 
	ON PRA.TYP_CODE = TPRA.TYP_CODE 
	ORDER BY PRA_NOM, PRA_PRENOM
END
GO

CREATE PROC PS_AffichTypePraticien AS
BEGIN
	SELECT TYP_CODE as code, TYP_LIBELLE as libelle
	FROM TYPE_PRATICIEN
END
GO

CREATE PROC PS_AffichPraticienPrecis  @TypePraticien varchar(40) AS
BEGIN
	SELECT PRA_NUM AS [N� Identifiant], PRA_NOM AS [Nom], PRA_PRENOM AS [Prenom] 
	FROM PRATICIEN PRA INNER JOIN TYPE_PRATICIEN TPRA 
	ON PRA.TYP_CODE = TPRA.TYP_CODE 
	WHERE PRA.TYP_CODE = @TypePraticien
	ORDER BY PRA_NOM, PRA_PRENOM
END
GO

CREATE PROC PS_CountPraticienPrecis @TypePraticien varchar(40) AS
BEGIN
	SELECT COUNT(*) 
	FROM PRATICIEN PRA INNER JOIN TYPE_PRATICIEN TPRA 
	ON PRA.TYP_CODE = TPRA.TYP_CODE 
	WHERE PRA.TYP_CODE = @TypePraticien
END
GO

CREATE PROC PS_ShowAdress @IdPraticien int AS
BEGIN
	SELECT PRA_ADRESSE 
	FROM PRATICIEN 
	WHERE PRA_NUM = @IdPraticien
END
GO

CREATE PROC PS_ShowLieu @IdPraticien int AS
BEGIN
	SELECT TYP_LIEU 
	FROM TYPE_PRATICIEN TPRA INNER JOIN PRATICIEN PRA 
	ON TPRA.TYP_CODE = PRA.TYP_CODE 
	WHERE PRA_NUM = @IdPraticien
END
GO

CREATE PROC PS_SelectionSurDate @Date DATE AS
BEGIN
	SELECT VIS_MATRICULE AS MATRICULE, 
	VIS_NOM AS NOM, 
	VIS_PRENOM AS PRENOM, 
	VIS_Adresse+', '+VIS_CP+', '+VIS_VILLE AS ADRESSE, 
	VIS_DATEEMBAUCHE AS 'DATE D''EMBAUCHE' 
	FROM VISITEUR 
	WHERE VIS_DATEEMBAUCHE = @Date
END
GO

CREATE PROC PS_AffVisiteurComplet AS
BEGIN
	SELECT VIS_MATRICULE AS MATRICULE, 
	VIS_NOM AS NOM, VIS_PRENOM AS PRENOM, 
	VIS_Adresse+', '+VIS_CP+', '+VIS_VILLE AS ADRESSE, 
	VIS_DATEEMBAUCHE AS 'DATE D''EMBAUCHE' 
	FROM VISITEUR
END
GO

CREATE PROC PS_LesDateEmbauches AS
BEGIN
	SELECT VIS_Dateembauche
	FROM VISITEUR
END
GO

CREATE PROC PS_SelectionNomParMatricule @Matricule varchar (38) AS
BEGIN
	SELECT VIS_NOM AS NOM
	FROM VISITEUR
	WHERE VIS_MATRICULE = @Matricule
END
GO

CREATE PROC PS_SelectionPrenomParMatricule @Matricule varchar (38) AS
BEGIN
	SELECT VIS_PRENOM AS PRENOM
	FROM VISITEUR
	WHERE VIS_MATRICULE = @Matricule
END
GO

CREATE PROC PS_SelectionAdresseParMatricule @Matricule varchar (38) AS
BEGIN
	SELECT VIS_ADRESSE AS ADRESSE
	FROM VISITEUR
	WHERE VIS_MATRICULE = @Matricule
END
GO

CREATE PROC PS_SelectionCPParMatricule @Matricule varchar (38) AS
BEGIN
	SELECT VIS_CP AS CP
	FROM VISITEUR
	WHERE VIS_MATRICULE = @Matricule
END
GO

CREATE PROC PS_SelectioNVilleParMatricule @Matricule varchar (38) AS
BEGIN
	SELECT VIS_VILLE AS VILLE
	FROM VISITEUR
	WHERE VIS_MATRICULE = @Matricule
END
GO

CREATE PROC PS_SelectionDateEmbaucheParMatricule @Matricule varchar (38) AS
BEGIN
	SELECT VIS_DATEEMBAUCHE AS 'DATE D''EMBAUCHE'
	FROM VISITEUR
	WHERE VIS_MATRICULE = @Matricule
END
GO